baseURL = "https://example.org/"
languageCode = "en-us"
title = "Microsoft Purview DLP and Sensitivity Labels Implementation Framework"
theme = "hextra"

# Hextra theme configuration
[params]
  # Enable dark mode
  darkMode = true
  
  # Theme color
  themeColor = "blue"
  
  # Enable search
  enableSearch = true
  
  # Enable table of contents
  enableTOC = true
  
  # Repository link
  gitRepo = "https://github.com/yourusername/microsoft-purview-framework"
  
  # Social links
  [params.social]
    github = "https://github.com/yourusername/microsoft-purview-framework"
    linkedin = "https://linkedin.com/company/yourcompany"

  # Footer configuration
  [params.footer]
    displayCopyright = true
    displayPoweredBy = true
    copyright = "Microsoft Purview DLP and Sensitivity Labels Implementation Framework"

[params.navbar]
  displayTitle = true
  displayLogo = false

[markup.goldmark.renderer]
  unsafe = true

# Configure page navigation
[params.page]
  # Show previous/next navigation
  navLinks = true
  # Show table of contents
  tocSide = "right"
  # Show breadcrumb
  breadcrumb = true
  # Show last updated time
  lastUpdated = true
