baseURL = "https://ayuzuf.github.io/purview/"
languageCode = "en-us"
title = "Microsoft Purview DLP and Sensitivity Labels Implementation Framework"
theme = "hextra"

# Hextra theme configuration
[params]
  # Enable dark mode
  darkMode = true

  # Theme color
  themeColor = "blue"

  # Enable search
  enableSearch = true

  # Enable table of contents
  enableTOC = true

  # Repository link
  gitRepo = "https://github.com/ayuzuf/purview"

  # Social links
  [params.social]
    github = "https://github.com/ayuzuf/purview"
    linkedin = "https://linkedin.com/company/yourcompany"

  # Footer configuration
  [params.footer]
    displayCopyright = true
    displayPoweredBy = true
    copyright = "Microsoft Purview DLP and Sensitivity Labels Implementation Framework"

# Navbar configuration
[params.navbar]
  displayTitle = true
  displayLogo = false

# Top navigation menu items
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "Docs"
    name = "Docs"
    url = "/docs/"
    weight = 3

# Configure page navigation
[params.page]
  # Show previous/next navigation
  navLinks = true
  # Show table of contents
  tocSide = "right"
  # Show breadcrumb
  breadcrumb = true
  # Show last updated time
  lastUpdated = true

[markup.goldmark.renderer]
  unsafe = true
